file <- read.csv("Followers.csv", sep="\t")
print(paste("Number of Followers:", nrow(file)))
print(paste("Mean:", mean(file[,2])))
print(paste("Standard Deviation:", sd(file[,2])))
print(paste("Median:", median(file[,2])))
